### ISSUE TITLE
Error with geckodriver?

### ISSUE THREAD

**Issue by jrmypttrsn** [twneale/tadpoles#1]
After running the third command ```./scripts/update.sh``` I'm getting the following error even though I have geckodriver installed and added to my PATH.
```
17:18:23 INFO app::__enter__: Starting xvfb display
17:18:23 INFO app::__enter__: Starting browser
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/app.py", line 290, in <module>
    download_images()
  File "/app/app.py", line 286, in download_images
    Client().main()
  File "/app/app.py", line 278, in main
    with self as client:
  File "/app/app.py", line 86, in __enter__
    self.br = self.browser = webdriver.Firefox()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 

ERROR: Not enough parameters for command 'sync'
`

Not sure what else to do. My daughter is going to a new daycare that doesn't use Tadpoles and I was want to back up the photos we have of her in the app.

**Comment by ChuckMac** [comment]
@jrmypttrsn still need help here or too late?  not the maintainer but I have been using this myself lately and making some changes.

From that error message I would guess something went wrong in the build script and didn't install geckodriver.

**Comment by jrmypttrsn** [comment]
@ChuckMac Too late but thanks for checking in!

**Comment by lindseymarrero** [comment]
@jrmypttrsn How did you resolve?  I'm having this issue now and really fighting with it.
