### ISSUE TITLE
what version of urllib3 should i use?

### ISSUE THREAD

**Issue by AdySan** [twneale/tadpoles#3]
I tried with the latest urllib3 version 1.23 installed via pip and I get this error.

```
adysan@adyNUC:~/git/tadpoles$ ./scripts/update.sh
15:12:59 INFO app::__enter__: Starting xvfb display
15:12:59 INFO app::__enter__: Starting browser
Traceback (most recent call last):
  File "/app/app.py", line 391, in <module>
    download_images()
  File "/app/app.py", line 387, in download_images
    Client().main()
  File "/app/app.py", line 379, in main
    with self as client:
  File "/app/app.py", line 87, in __enter__
    self.br = self.browser = webdriver.Firefox()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 167, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 251, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/remote_connection.py", line 375, in execute

    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 79, in request
    **urlopen_kw)
  File "/usr/lib/python3/dist-packages/urllib3/request.py", line 142, in request_encode_body
    **urlopen_kw)
TypeError: urlopen() got multiple values for keyword argument 'body'
```

**Comment by kevinmbowen** [comment]
I had the same error.  My issue was I was installing urllib3 locally on my machine and not via the Docker Container. 

Did you install urllib3 via pip on your local machine?  

If so try to edit your "Dockerfile" and add the following line:

**RUN pip3 install urllib3 --upgrade**

![image](https://user-images.githubusercontent.com/26546724/44832018-0d1bd600-abf7-11e8-86af-995fdb63bc1e.png)

And then re-run your Docker build

**Comment by AdySan** [comment]
Thanks, that makes sense. However, I started using this script as I wasn't really interested in dumping the files to S3.

https://gist.github.com/AdySan/047408a0aee487c2b170e22e4c66cf37
