### ISSUE TITLE
ImportError: No module named 'eappcyber'

### ISSUE THREAD

**Issue by frankea** [twneale/tadpoles#6]
When running the main script, encountering the following error:

```
➜  tadpoles git:(master) ./scripts/update.sh

Traceback (most recent call last):
  File "/app/app.py", line 20, in <module>
    from firefox import Firefox
  File "/app/firefox.py", line 8, in <module>
    from eappcyber.meta import Metadata
ImportError: No module named 'eappcyber'
```

And unfortunately, I can't seem to find much info on "eappcyber" to install it.

**Comment by kronik1** [comment]
Having the same problem

**Comment by lindseymarrero** [comment]
Also having the same problem.  And google comes up with nothing for eappcyber.  Is it a missing reference, @twneale ?
